ol.proj.proj4.register(proj4);
//ol.proj.get("EPSG:3067").setExtent([-58121.686932, 6536570.460040, 981314.431365, 7386505.036211]);
var wms_layers = [];


        var lyr_OpenStreetMap_0 = new ol.layer.Tile({
            'title': 'OpenStreetMap',
            'type':'base',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
            attributions: ' ',
                url: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'
            })
        });
var format_50kmrajavyhykeFINO_1 = new ol.format.GeoJSON();
var features_50kmrajavyhykeFINO_1 = format_50kmrajavyhykeFINO_1.readFeatures(json_50kmrajavyhykeFINO_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3067'});
var jsonSource_50kmrajavyhykeFINO_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_50kmrajavyhykeFINO_1.addFeatures(features_50kmrajavyhykeFINO_1);
var lyr_50kmrajavyhykeFINO_1 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_50kmrajavyhykeFINO_1, 
                style: style_50kmrajavyhykeFINO_1,
                popuplayertitle: '50km rajavyöhyke FI-NO',
                interactive: false,
                title: '<img src="styles/legend/50kmrajavyhykeFINO_1.png" /> 50km rajavyöhyke Suomen ja Norjan välisestä valtakunnanrajasta' +
                '<p>Suurin sallittu lähetysteho 50km rajavyöhykkeellä on 25W (PEP / CW).</p>'
            });
var format_50kmrajavyhykeFIRU_2 = new ol.format.GeoJSON();
var features_50kmrajavyhykeFIRU_2 = format_50kmrajavyhykeFIRU_2.readFeatures(json_50kmrajavyhykeFIRU_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3067'});
var jsonSource_50kmrajavyhykeFIRU_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_50kmrajavyhykeFIRU_2.addFeatures(features_50kmrajavyhykeFIRU_2);
var lyr_50kmrajavyhykeFIRU_2 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_50kmrajavyhykeFIRU_2, 
                style: style_50kmrajavyhykeFIRU_2,
                popuplayertitle: '50km rajavyöhyke FI-RU',
                interactive: false,
                title: '<img src="styles/legend/50kmrajavyhykeFIRU_2.png" /> 50km rajavyöhyke Suomen ja Venäjän Federaation välisestä valtakunnanrajasta' +
                '<p>Suurin sallittu lähetysteho on 25W (PEP / CW)' +
                '<br>Lähetinantennin pääsäteilykeila ei saa osoittaa suuntaan 0-180 astetta.</p>'
            });
var format_70MHzkielletytkunnat_3 = new ol.format.GeoJSON();
var features_70MHzkielletytkunnat_3 = format_70MHzkielletytkunnat_3.readFeatures(json_70MHzkielletytkunnat_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3067'});
var jsonSource_70MHzkielletytkunnat_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_70MHzkielletytkunnat_3.addFeatures(features_70MHzkielletytkunnat_3);
var lyr_70MHzkielletytkunnat_3 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_70MHzkielletytkunnat_3, 
                style: style_70MHzkielletytkunnat_3,
                popuplayertitle: '70MHz kielletyt kunnat',
                interactive: false,
                title: '<img src="styles/legend/70MHzkielletytkunnat_3.png" /> 70MHz kielletyt kunnat' +
                '<p>70MHz radioamatöörilähettimiä ei saa käyttää seuraavien kuntien alueella:' +
                '<br>Lieksa, Ilomantsi, Joensuu, Kontiolahti, Polvijärvi, Juuka, Nurmes,' +
                '<br>Valtimo (nyk. Nurmes), Kuhmo, Hyrynsalmi, Suomussalmi, Ristijärvi ja Sotkamo.'
            });

lyr_OpenStreetMap_0.setVisible(true);lyr_50kmrajavyhykeFINO_1.setVisible(true);lyr_50kmrajavyhykeFIRU_2.setVisible(true);lyr_70MHzkielletytkunnat_3.setVisible(true);
var layersList = [lyr_OpenStreetMap_0,lyr_50kmrajavyhykeFINO_1,lyr_50kmrajavyhykeFIRU_2,lyr_70MHzkielletytkunnat_3];
lyr_50kmrajavyhykeFINO_1.set('fieldAliases', {'fid': 'fid', 'NAME_LEN': 'NAME_LEN', 'NAME_FR': 'NAME_FR', 'ISO_A3': 'ISO_A3', 'ISO_A2': 'ISO_A2', 'ABBREV_LEN': 'ABBREV_LEN', 'FIPS_10_': 'FIPS_10_', 'ECONOMY': 'ECONOMY', 'ADM0_A3_US': 'ADM0_A3_US', 'NAME_NL': 'NAME_NL', 'NAME_SORT': 'NAME_SORT', 'TINY': 'TINY', 'ADM0_DIF': 'ADM0_DIF', 'SUBREGION': 'SUBREGION', 'ADM0_A3_UN': 'ADM0_A3_UN', 'NAME_RU': 'NAME_RU', 'GDP_MD_EST': 'GDP_MD_EST', 'NAME_ES': 'NAME_ES', 'WIKIPEDIA': 'WIKIPEDIA', 'GDP_YEAR': 'GDP_YEAR', 'NAME_EL': 'NAME_EL', 'NAME_EN': 'NAME_EN', 'BRK_DIFF': 'BRK_DIFF', 'NAME_VI': 'NAME_VI', 'POP_RANK': 'POP_RANK', 'ISO_N3': 'ISO_N3', 'BRK_NAME': 'BRK_NAME', 'REGION_UN': 'REGION_UN', 'REGION_WB': 'REGION_WB', 'NOTE_BRK': 'NOTE_BRK', 'SUBUNIT': 'SUBUNIT', 'GU_A3': 'GU_A3', 'NAME_HU': 'NAME_HU', 'MAPCOLOR7': 'MAPCOLOR7', 'MAPCOLOR8': 'MAPCOLOR8', 'MAPCOLOR9': 'MAPCOLOR9', 'NAME_HI': 'NAME_HI', 'FORMAL_FR': 'FORMAL_FR', 'SU_A3': 'SU_A3', 'POP_EST': 'POP_EST', 'GEOUNIT': 'GEOUNIT', 'HOMEPART': 'HOMEPART', 'NAME_ALT': 'NAME_ALT', 'NAME_PL': 'NAME_PL', 'BRK_A3': 'BRK_A3', 'NAME_PT': 'NAME_PT', 'WOE_ID': 'WOE_ID', 'scalerank': 'scalerank', 'LASTCENSUS': 'LASTCENSUS', 'UN_A3': 'UN_A3', 'LABELRANK': 'LABELRANK', 'NAME_SV': 'NAME_SV', 'NAME_BN': 'NAME_BN', 'ABBREV': 'ABBREV', 'MIN_ZOOM': 'MIN_ZOOM', 'ADM0_A3_IS': 'ADM0_A3_IS', 'NAME_JA': 'NAME_JA', 'ADMIN': 'ADMIN', 'NAME_AR': 'NAME_AR', 'SOVEREIGNT': 'SOVEREIGNT', 'ISO_A3_EH': 'ISO_A3_EH', 'MAX_LABEL': 'MAX_LABEL', 'NAME_IT': 'NAME_IT', 'NAME': 'NAME', 'INCOME_GRP': 'INCOME_GRP', 'SOV_A3': 'SOV_A3', 'NOTE_ADM0': 'NOTE_ADM0', 'NAME_ID': 'NAME_ID', 'TYPE': 'TYPE', 'NAME_CIAWF': 'NAME_CIAWF', 'NAME_DE': 'NAME_DE', 'ADM0_A3': 'ADM0_A3', 'WIKIDATAID': 'WIKIDATAID', 'POSTAL': 'POSTAL', 'LONG_LEN': 'LONG_LEN', 'WOE_ID_EH': 'WOE_ID_EH', 'LEVEL': 'LEVEL', 'FORMAL_EN': 'FORMAL_EN', 'POP_YEAR': 'POP_YEAR', 'WOE_NOTE': 'WOE_NOTE', 'ADM0_A3_WB': 'ADM0_A3_WB', 'CONTINENT': 'CONTINENT', 'NAME_TR': 'NAME_TR', 'GEOU_DIF': 'GEOU_DIF', 'MAPCOLOR13': 'MAPCOLOR13', 'BRK_GROUP': 'BRK_GROUP', 'SU_DIF': 'SU_DIF', 'featurecla': 'featurecla', 'MIN_LABEL': 'MIN_LABEL', 'NAME_ZH': 'NAME_ZH', 'WB_A2': 'WB_A2', 'WB_A3': 'WB_A3', 'NAME_KO': 'NAME_KO', 'NE_ID': 'NE_ID', 'NAME_LONG': 'NAME_LONG', });
lyr_50kmrajavyhykeFIRU_2.set('fieldAliases', {'fid': 'fid', 'NAME_LEN': 'NAME_LEN', 'NAME_FR': 'NAME_FR', 'ISO_A3': 'ISO_A3', 'ISO_A2': 'ISO_A2', 'ABBREV_LEN': 'ABBREV_LEN', 'FIPS_10_': 'FIPS_10_', 'ECONOMY': 'ECONOMY', 'ADM0_A3_US': 'ADM0_A3_US', 'NAME_NL': 'NAME_NL', 'NAME_SORT': 'NAME_SORT', 'TINY': 'TINY', 'ADM0_DIF': 'ADM0_DIF', 'SUBREGION': 'SUBREGION', 'ADM0_A3_UN': 'ADM0_A3_UN', 'NAME_RU': 'NAME_RU', 'GDP_MD_EST': 'GDP_MD_EST', 'NAME_ES': 'NAME_ES', 'WIKIPEDIA': 'WIKIPEDIA', 'GDP_YEAR': 'GDP_YEAR', 'NAME_EL': 'NAME_EL', 'NAME_EN': 'NAME_EN', 'BRK_DIFF': 'BRK_DIFF', 'NAME_VI': 'NAME_VI', 'POP_RANK': 'POP_RANK', 'ISO_N3': 'ISO_N3', 'BRK_NAME': 'BRK_NAME', 'REGION_UN': 'REGION_UN', 'REGION_WB': 'REGION_WB', 'NOTE_BRK': 'NOTE_BRK', 'SUBUNIT': 'SUBUNIT', 'GU_A3': 'GU_A3', 'NAME_HU': 'NAME_HU', 'MAPCOLOR7': 'MAPCOLOR7', 'MAPCOLOR8': 'MAPCOLOR8', 'MAPCOLOR9': 'MAPCOLOR9', 'NAME_HI': 'NAME_HI', 'FORMAL_FR': 'FORMAL_FR', 'SU_A3': 'SU_A3', 'POP_EST': 'POP_EST', 'GEOUNIT': 'GEOUNIT', 'HOMEPART': 'HOMEPART', 'NAME_ALT': 'NAME_ALT', 'NAME_PL': 'NAME_PL', 'BRK_A3': 'BRK_A3', 'NAME_PT': 'NAME_PT', 'WOE_ID': 'WOE_ID', 'scalerank': 'scalerank', 'LASTCENSUS': 'LASTCENSUS', 'UN_A3': 'UN_A3', 'LABELRANK': 'LABELRANK', 'NAME_SV': 'NAME_SV', 'NAME_BN': 'NAME_BN', 'ABBREV': 'ABBREV', 'MIN_ZOOM': 'MIN_ZOOM', 'ADM0_A3_IS': 'ADM0_A3_IS', 'NAME_JA': 'NAME_JA', 'ADMIN': 'ADMIN', 'NAME_AR': 'NAME_AR', 'SOVEREIGNT': 'SOVEREIGNT', 'ISO_A3_EH': 'ISO_A3_EH', 'MAX_LABEL': 'MAX_LABEL', 'NAME_IT': 'NAME_IT', 'NAME': 'NAME', 'INCOME_GRP': 'INCOME_GRP', 'SOV_A3': 'SOV_A3', 'NOTE_ADM0': 'NOTE_ADM0', 'NAME_ID': 'NAME_ID', 'TYPE': 'TYPE', 'NAME_CIAWF': 'NAME_CIAWF', 'NAME_DE': 'NAME_DE', 'ADM0_A3': 'ADM0_A3', 'WIKIDATAID': 'WIKIDATAID', 'POSTAL': 'POSTAL', 'LONG_LEN': 'LONG_LEN', 'WOE_ID_EH': 'WOE_ID_EH', 'LEVEL': 'LEVEL', 'FORMAL_EN': 'FORMAL_EN', 'POP_YEAR': 'POP_YEAR', 'WOE_NOTE': 'WOE_NOTE', 'ADM0_A3_WB': 'ADM0_A3_WB', 'CONTINENT': 'CONTINENT', 'NAME_TR': 'NAME_TR', 'GEOU_DIF': 'GEOU_DIF', 'MAPCOLOR13': 'MAPCOLOR13', 'BRK_GROUP': 'BRK_GROUP', 'SU_DIF': 'SU_DIF', 'featurecla': 'featurecla', 'MIN_LABEL': 'MIN_LABEL', 'NAME_ZH': 'NAME_ZH', 'WB_A2': 'WB_A2', 'WB_A3': 'WB_A3', 'NAME_KO': 'NAME_KO', 'NE_ID': 'NE_ID', 'NAME_LONG': 'NAME_LONG', });
lyr_70MHzkielletytkunnat_3.set('fieldAliases', {'GML_ID': 'GML_ID', 'NATCODE': 'NATCODE', 'NAMEFIN': 'NAMEFIN', 'NAMESWE': 'NAMESWE', 'LANDAREA': 'LANDAREA', 'FRESHWAREA': 'FRESHWAREA', 'SEAWAREA': 'SEAWAREA', 'TOTALAREA': 'TOTALAREA', });
lyr_50kmrajavyhykeFINO_1.set('fieldImages', {'fid': 'TextEdit', 'NAME_LEN': 'TextEdit', 'NAME_FR': 'TextEdit', 'ISO_A3': 'TextEdit', 'ISO_A2': 'TextEdit', 'ABBREV_LEN': 'TextEdit', 'FIPS_10_': 'TextEdit', 'ECONOMY': 'TextEdit', 'ADM0_A3_US': 'TextEdit', 'NAME_NL': 'TextEdit', 'NAME_SORT': 'TextEdit', 'TINY': 'TextEdit', 'ADM0_DIF': 'TextEdit', 'SUBREGION': 'TextEdit', 'ADM0_A3_UN': 'TextEdit', 'NAME_RU': 'TextEdit', 'GDP_MD_EST': 'TextEdit', 'NAME_ES': 'TextEdit', 'WIKIPEDIA': 'TextEdit', 'GDP_YEAR': 'TextEdit', 'NAME_EL': 'TextEdit', 'NAME_EN': 'TextEdit', 'BRK_DIFF': 'TextEdit', 'NAME_VI': 'TextEdit', 'POP_RANK': 'TextEdit', 'ISO_N3': 'TextEdit', 'BRK_NAME': 'TextEdit', 'REGION_UN': 'TextEdit', 'REGION_WB': 'TextEdit', 'NOTE_BRK': 'TextEdit', 'SUBUNIT': 'TextEdit', 'GU_A3': 'TextEdit', 'NAME_HU': 'TextEdit', 'MAPCOLOR7': 'TextEdit', 'MAPCOLOR8': 'TextEdit', 'MAPCOLOR9': 'TextEdit', 'NAME_HI': 'TextEdit', 'FORMAL_FR': 'TextEdit', 'SU_A3': 'TextEdit', 'POP_EST': 'TextEdit', 'GEOUNIT': 'TextEdit', 'HOMEPART': 'TextEdit', 'NAME_ALT': 'TextEdit', 'NAME_PL': 'TextEdit', 'BRK_A3': 'TextEdit', 'NAME_PT': 'TextEdit', 'WOE_ID': 'TextEdit', 'scalerank': 'TextEdit', 'LASTCENSUS': 'TextEdit', 'UN_A3': 'TextEdit', 'LABELRANK': 'TextEdit', 'NAME_SV': 'TextEdit', 'NAME_BN': 'TextEdit', 'ABBREV': 'TextEdit', 'MIN_ZOOM': 'TextEdit', 'ADM0_A3_IS': 'TextEdit', 'NAME_JA': 'TextEdit', 'ADMIN': 'TextEdit', 'NAME_AR': 'TextEdit', 'SOVEREIGNT': 'TextEdit', 'ISO_A3_EH': 'TextEdit', 'MAX_LABEL': 'TextEdit', 'NAME_IT': 'TextEdit', 'NAME': 'TextEdit', 'INCOME_GRP': 'TextEdit', 'SOV_A3': 'TextEdit', 'NOTE_ADM0': 'TextEdit', 'NAME_ID': 'TextEdit', 'TYPE': 'TextEdit', 'NAME_CIAWF': 'TextEdit', 'NAME_DE': 'TextEdit', 'ADM0_A3': 'TextEdit', 'WIKIDATAID': 'TextEdit', 'POSTAL': 'TextEdit', 'LONG_LEN': 'TextEdit', 'WOE_ID_EH': 'TextEdit', 'LEVEL': 'TextEdit', 'FORMAL_EN': 'TextEdit', 'POP_YEAR': 'TextEdit', 'WOE_NOTE': 'TextEdit', 'ADM0_A3_WB': 'TextEdit', 'CONTINENT': 'TextEdit', 'NAME_TR': 'TextEdit', 'GEOU_DIF': 'TextEdit', 'MAPCOLOR13': 'TextEdit', 'BRK_GROUP': 'TextEdit', 'SU_DIF': 'TextEdit', 'featurecla': 'TextEdit', 'MIN_LABEL': 'TextEdit', 'NAME_ZH': 'TextEdit', 'WB_A2': 'TextEdit', 'WB_A3': 'TextEdit', 'NAME_KO': 'TextEdit', 'NE_ID': 'TextEdit', 'NAME_LONG': 'TextEdit', });
lyr_50kmrajavyhykeFIRU_2.set('fieldImages', {'fid': 'TextEdit', 'NAME_LEN': 'TextEdit', 'NAME_FR': 'TextEdit', 'ISO_A3': 'TextEdit', 'ISO_A2': 'TextEdit', 'ABBREV_LEN': 'TextEdit', 'FIPS_10_': 'TextEdit', 'ECONOMY': 'TextEdit', 'ADM0_A3_US': 'TextEdit', 'NAME_NL': 'TextEdit', 'NAME_SORT': 'TextEdit', 'TINY': 'TextEdit', 'ADM0_DIF': 'TextEdit', 'SUBREGION': 'TextEdit', 'ADM0_A3_UN': 'TextEdit', 'NAME_RU': 'TextEdit', 'GDP_MD_EST': 'TextEdit', 'NAME_ES': 'TextEdit', 'WIKIPEDIA': 'TextEdit', 'GDP_YEAR': 'TextEdit', 'NAME_EL': 'TextEdit', 'NAME_EN': 'TextEdit', 'BRK_DIFF': 'TextEdit', 'NAME_VI': 'TextEdit', 'POP_RANK': 'TextEdit', 'ISO_N3': 'TextEdit', 'BRK_NAME': 'TextEdit', 'REGION_UN': 'TextEdit', 'REGION_WB': 'TextEdit', 'NOTE_BRK': 'TextEdit', 'SUBUNIT': 'TextEdit', 'GU_A3': 'TextEdit', 'NAME_HU': 'TextEdit', 'MAPCOLOR7': 'TextEdit', 'MAPCOLOR8': 'TextEdit', 'MAPCOLOR9': 'TextEdit', 'NAME_HI': 'TextEdit', 'FORMAL_FR': 'TextEdit', 'SU_A3': 'TextEdit', 'POP_EST': 'TextEdit', 'GEOUNIT': 'TextEdit', 'HOMEPART': 'TextEdit', 'NAME_ALT': 'TextEdit', 'NAME_PL': 'TextEdit', 'BRK_A3': 'TextEdit', 'NAME_PT': 'TextEdit', 'WOE_ID': 'TextEdit', 'scalerank': 'TextEdit', 'LASTCENSUS': 'TextEdit', 'UN_A3': 'TextEdit', 'LABELRANK': 'TextEdit', 'NAME_SV': 'TextEdit', 'NAME_BN': 'TextEdit', 'ABBREV': 'TextEdit', 'MIN_ZOOM': 'TextEdit', 'ADM0_A3_IS': 'TextEdit', 'NAME_JA': 'TextEdit', 'ADMIN': 'TextEdit', 'NAME_AR': 'TextEdit', 'SOVEREIGNT': 'TextEdit', 'ISO_A3_EH': 'TextEdit', 'MAX_LABEL': 'TextEdit', 'NAME_IT': 'TextEdit', 'NAME': 'TextEdit', 'INCOME_GRP': 'TextEdit', 'SOV_A3': 'TextEdit', 'NOTE_ADM0': 'TextEdit', 'NAME_ID': 'TextEdit', 'TYPE': 'TextEdit', 'NAME_CIAWF': 'TextEdit', 'NAME_DE': 'TextEdit', 'ADM0_A3': 'TextEdit', 'WIKIDATAID': 'TextEdit', 'POSTAL': 'TextEdit', 'LONG_LEN': 'TextEdit', 'WOE_ID_EH': 'TextEdit', 'LEVEL': 'TextEdit', 'FORMAL_EN': 'TextEdit', 'POP_YEAR': 'TextEdit', 'WOE_NOTE': 'TextEdit', 'ADM0_A3_WB': 'TextEdit', 'CONTINENT': 'TextEdit', 'NAME_TR': 'TextEdit', 'GEOU_DIF': 'TextEdit', 'MAPCOLOR13': 'TextEdit', 'BRK_GROUP': 'TextEdit', 'SU_DIF': 'TextEdit', 'featurecla': 'TextEdit', 'MIN_LABEL': 'TextEdit', 'NAME_ZH': 'TextEdit', 'WB_A2': 'TextEdit', 'WB_A3': 'TextEdit', 'NAME_KO': 'TextEdit', 'NE_ID': 'TextEdit', 'NAME_LONG': 'TextEdit', });
lyr_70MHzkielletytkunnat_3.set('fieldImages', {'GML_ID': 'TextEdit', 'NATCODE': 'TextEdit', 'NAMEFIN': 'TextEdit', 'NAMESWE': 'TextEdit', 'LANDAREA': 'TextEdit', 'FRESHWAREA': 'TextEdit', 'SEAWAREA': 'TextEdit', 'TOTALAREA': 'TextEdit', });
lyr_50kmrajavyhykeFINO_1.set('fieldLabels', {'fid': 'no label', 'NAME_LEN': 'no label', 'NAME_FR': 'no label', 'ISO_A3': 'no label', 'ISO_A2': 'no label', 'ABBREV_LEN': 'no label', 'FIPS_10_': 'no label', 'ECONOMY': 'no label', 'ADM0_A3_US': 'no label', 'NAME_NL': 'no label', 'NAME_SORT': 'no label', 'TINY': 'no label', 'ADM0_DIF': 'no label', 'SUBREGION': 'no label', 'ADM0_A3_UN': 'no label', 'NAME_RU': 'no label', 'GDP_MD_EST': 'no label', 'NAME_ES': 'no label', 'WIKIPEDIA': 'no label', 'GDP_YEAR': 'no label', 'NAME_EL': 'no label', 'NAME_EN': 'no label', 'BRK_DIFF': 'no label', 'NAME_VI': 'no label', 'POP_RANK': 'no label', 'ISO_N3': 'no label', 'BRK_NAME': 'no label', 'REGION_UN': 'no label', 'REGION_WB': 'no label', 'NOTE_BRK': 'no label', 'SUBUNIT': 'no label', 'GU_A3': 'no label', 'NAME_HU': 'no label', 'MAPCOLOR7': 'no label', 'MAPCOLOR8': 'no label', 'MAPCOLOR9': 'no label', 'NAME_HI': 'no label', 'FORMAL_FR': 'no label', 'SU_A3': 'no label', 'POP_EST': 'no label', 'GEOUNIT': 'no label', 'HOMEPART': 'no label', 'NAME_ALT': 'no label', 'NAME_PL': 'no label', 'BRK_A3': 'no label', 'NAME_PT': 'no label', 'WOE_ID': 'no label', 'scalerank': 'no label', 'LASTCENSUS': 'no label', 'UN_A3': 'no label', 'LABELRANK': 'no label', 'NAME_SV': 'no label', 'NAME_BN': 'no label', 'ABBREV': 'no label', 'MIN_ZOOM': 'no label', 'ADM0_A3_IS': 'no label', 'NAME_JA': 'no label', 'ADMIN': 'no label', 'NAME_AR': 'no label', 'SOVEREIGNT': 'no label', 'ISO_A3_EH': 'no label', 'MAX_LABEL': 'no label', 'NAME_IT': 'no label', 'NAME': 'no label', 'INCOME_GRP': 'no label', 'SOV_A3': 'no label', 'NOTE_ADM0': 'no label', 'NAME_ID': 'no label', 'TYPE': 'no label', 'NAME_CIAWF': 'no label', 'NAME_DE': 'no label', 'ADM0_A3': 'no label', 'WIKIDATAID': 'no label', 'POSTAL': 'no label', 'LONG_LEN': 'no label', 'WOE_ID_EH': 'no label', 'LEVEL': 'no label', 'FORMAL_EN': 'no label', 'POP_YEAR': 'no label', 'WOE_NOTE': 'no label', 'ADM0_A3_WB': 'no label', 'CONTINENT': 'no label', 'NAME_TR': 'no label', 'GEOU_DIF': 'no label', 'MAPCOLOR13': 'no label', 'BRK_GROUP': 'no label', 'SU_DIF': 'no label', 'featurecla': 'no label', 'MIN_LABEL': 'no label', 'NAME_ZH': 'no label', 'WB_A2': 'no label', 'WB_A3': 'no label', 'NAME_KO': 'no label', 'NE_ID': 'no label', 'NAME_LONG': 'no label', });
lyr_50kmrajavyhykeFIRU_2.set('fieldLabels', {'fid': 'no label', 'NAME_LEN': 'no label', 'NAME_FR': 'no label', 'ISO_A3': 'no label', 'ISO_A2': 'no label', 'ABBREV_LEN': 'no label', 'FIPS_10_': 'no label', 'ECONOMY': 'no label', 'ADM0_A3_US': 'no label', 'NAME_NL': 'no label', 'NAME_SORT': 'no label', 'TINY': 'no label', 'ADM0_DIF': 'no label', 'SUBREGION': 'no label', 'ADM0_A3_UN': 'no label', 'NAME_RU': 'no label', 'GDP_MD_EST': 'no label', 'NAME_ES': 'no label', 'WIKIPEDIA': 'no label', 'GDP_YEAR': 'no label', 'NAME_EL': 'no label', 'NAME_EN': 'no label', 'BRK_DIFF': 'no label', 'NAME_VI': 'no label', 'POP_RANK': 'no label', 'ISO_N3': 'no label', 'BRK_NAME': 'no label', 'REGION_UN': 'no label', 'REGION_WB': 'no label', 'NOTE_BRK': 'no label', 'SUBUNIT': 'no label', 'GU_A3': 'no label', 'NAME_HU': 'no label', 'MAPCOLOR7': 'no label', 'MAPCOLOR8': 'no label', 'MAPCOLOR9': 'no label', 'NAME_HI': 'no label', 'FORMAL_FR': 'no label', 'SU_A3': 'no label', 'POP_EST': 'no label', 'GEOUNIT': 'no label', 'HOMEPART': 'no label', 'NAME_ALT': 'no label', 'NAME_PL': 'no label', 'BRK_A3': 'no label', 'NAME_PT': 'no label', 'WOE_ID': 'no label', 'scalerank': 'no label', 'LASTCENSUS': 'no label', 'UN_A3': 'no label', 'LABELRANK': 'no label', 'NAME_SV': 'no label', 'NAME_BN': 'no label', 'ABBREV': 'no label', 'MIN_ZOOM': 'no label', 'ADM0_A3_IS': 'no label', 'NAME_JA': 'no label', 'ADMIN': 'no label', 'NAME_AR': 'no label', 'SOVEREIGNT': 'no label', 'ISO_A3_EH': 'no label', 'MAX_LABEL': 'no label', 'NAME_IT': 'no label', 'NAME': 'no label', 'INCOME_GRP': 'no label', 'SOV_A3': 'no label', 'NOTE_ADM0': 'no label', 'NAME_ID': 'no label', 'TYPE': 'no label', 'NAME_CIAWF': 'no label', 'NAME_DE': 'no label', 'ADM0_A3': 'no label', 'WIKIDATAID': 'no label', 'POSTAL': 'no label', 'LONG_LEN': 'no label', 'WOE_ID_EH': 'no label', 'LEVEL': 'no label', 'FORMAL_EN': 'no label', 'POP_YEAR': 'no label', 'WOE_NOTE': 'no label', 'ADM0_A3_WB': 'no label', 'CONTINENT': 'no label', 'NAME_TR': 'no label', 'GEOU_DIF': 'no label', 'MAPCOLOR13': 'no label', 'BRK_GROUP': 'no label', 'SU_DIF': 'no label', 'featurecla': 'no label', 'MIN_LABEL': 'no label', 'NAME_ZH': 'no label', 'WB_A2': 'no label', 'WB_A3': 'no label', 'NAME_KO': 'no label', 'NE_ID': 'no label', 'NAME_LONG': 'no label', });
lyr_70MHzkielletytkunnat_3.set('fieldLabels', {'GML_ID': 'no label', 'NATCODE': 'no label', 'NAMEFIN': 'inline label - always visible', 'NAMESWE': 'no label', 'LANDAREA': 'no label', 'FRESHWAREA': 'no label', 'SEAWAREA': 'no label', 'TOTALAREA': 'no label', });
lyr_70MHzkielletytkunnat_3.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});